"""HTML report generation."""

import logging
from datetime import datetime
from typing import Optional
from dataclasses import asdict

from ssl_tester.models import CheckResult, Severity, Rating

logger = logging.getLogger(__name__)


def generate_html_report(result: CheckResult) -> str:
    """
    Generate HTML report with professional styling.
    
    Args:
        result: CheckResult to report
        
    Returns:
        HTML string
    """
    rating = result.rating or Rating.C
    rating_class = _get_rating_class(rating)
    
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SSL/TLS Certificate Check Report - {result.target_host}</title>
    <style>
        {_get_css_styles()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>SSL/TLS Certificate Check Report</h1>
            <div class="header-info">
                <div class="info-item">
                    <strong>Target:</strong> {result.target_host}:{result.target_port}
                </div>
                {f'<div class="info-item"><strong>Service:</strong> {result.service_type}</div>' if result.service_type else ''}
                <div class="info-item">
                    <strong>Timestamp:</strong> {result.timestamp.strftime('%Y-%m-%d %H:%M:%S UTC')}
                </div>
            </div>
        </header>
        
        <div class="rating-badge rating-{rating_class}">
            <div class="rating-label">Security Rating</div>
            <div class="rating-value">{rating.value}</div>
        </div>
        
        {f'''<div class="rating-reasons">
            <h3>Downgrade Reasons:</h3>
            <ul>
                {''.join(f'<li>{reason}</li>' for reason in result.rating_reasons)}
            </ul>
        </div>''' if result.rating_reasons else ''}
        
        <div class="summary-box">
            <h2>Summary</h2>
            <div class="severity-badge severity-{result.overall_severity.value.lower()}">
                {result.overall_severity.value}
            </div>
            <p class="summary-text">{result.summary or "All checks passed successfully"}</p>
        </div>
        
        {_generate_certificate_section(result)}
        {_generate_protocol_section(result)}
        {_generate_cipher_section(result)}
        {_generate_vulnerability_section(result)}
        {_generate_security_section(result)}
        {_generate_crl_section(result)}
        {_generate_ocsp_section(result)}
        
        <footer>
            <p>Generated by SSL-Tester</p>
        </footer>
    </div>
</body>
</html>"""
    
    return html


def _get_css_styles() -> str:
    """Get CSS styles for HTML report."""
    return """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            background-color: #f5f5f5;
            padding: 20px;
        }
        
        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            overflow: hidden;
        }
        
        header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
        }
        
        header h1 {
            font-size: 2em;
            margin-bottom: 15px;
        }
        
        .header-info {
            display: flex;
            flex-wrap: wrap;
            gap: 20px;
        }
        
        .info-item {
            font-size: 0.9em;
        }
        
        .rating-badge {
            text-align: center;
            padding: 30px;
            margin: 20px;
            border-radius: 8px;
            font-weight: bold;
        }
        
        .rating-label {
            font-size: 0.9em;
            opacity: 0.9;
            margin-bottom: 5px;
        }
        
        .rating-value {
            font-size: 4em;
            font-weight: bold;
        }
        
        .rating-a-plus-plus { background: #10b981; color: white; }
        .rating-a-plus { background: #059669; color: white; }
        .rating-a { background: #34d399; color: white; }
        .rating-b { background: #fbbf24; color: #78350f; }
        .rating-c { background: #f59e0b; color: white; }
        .rating-d { background: #ef4444; color: white; }
        .rating-e { background: #dc2626; color: white; }
        .rating-f { background: #991b1b; color: white; }
        
        .rating-reasons {
            margin: 20px;
            padding: 20px;
            background: #fef3c7;
            border-radius: 8px;
            border-left: 4px solid #f59e0b;
        }
        
        .rating-reasons h3 {
            margin-bottom: 10px;
            color: #78350f;
        }
        
        .rating-reasons ul {
            margin-left: 20px;
            color: #78350f;
        }
        
        .rating-reasons li {
            margin-bottom: 5px;
        }
        
        .summary-box {
            margin: 20px;
            padding: 20px;
            background: #f9fafb;
            border-radius: 8px;
            border-left: 4px solid #667eea;
        }
        
        .summary-box h2 {
            margin-bottom: 15px;
            color: #667eea;
        }
        
        .severity-badge {
            display: inline-block;
            padding: 5px 15px;
            border-radius: 4px;
            font-weight: bold;
            margin-bottom: 10px;
        }
        
        .severity-ok { background: #10b981; color: white; }
        .severity-warn { background: #f59e0b; color: white; }
        .severity-fail { background: #ef4444; color: white; }
        
        .summary-text {
            margin-top: 10px;
            line-height: 1.8;
        }
        
        section {
            margin: 20px;
            padding: 20px;
            background: white;
            border-radius: 8px;
            border: 1px solid #e5e7eb;
        }
        
        section h2 {
            color: #667eea;
            margin-bottom: 15px;
            padding-bottom: 10px;
            border-bottom: 2px solid #e5e7eb;
        }
        
        .check-item {
            margin: 15px 0;
            padding: 15px;
            background: #f9fafb;
            border-radius: 6px;
            border-left: 4px solid #e5e7eb;
        }
        
        .check-item.ok { border-left-color: #10b981; }
        .check-item.warn { border-left-color: #f59e0b; }
        .check-item.fail { border-left-color: #ef4444; }
        
        .check-label {
            font-weight: bold;
            margin-bottom: 5px;
        }
        
        .check-value {
            color: #6b7280;
        }
        
        .vulnerability-item {
            margin: 10px 0;
            padding: 15px;
            border-radius: 6px;
        }
        
        .vulnerability-item.vulnerable {
            background: #fee2e2;
            border-left: 4px solid #ef4444;
        }
        
        .vulnerability-item.safe {
            background: #d1fae5;
            border-left: 4px solid #10b981;
        }
        
        .cipher-list {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
            gap: 10px;
            margin-top: 10px;
        }
        
        .cipher-item {
            padding: 8px;
            background: #f3f4f6;
            border-radius: 4px;
            font-family: monospace;
            font-size: 0.9em;
        }
        
        .cipher-item.weak {
            background: #fee2e2;
            color: #991b1b;
        }
        
        footer {
            text-align: center;
            padding: 20px;
            color: #6b7280;
            border-top: 1px solid #e5e7eb;
        }
        
        @media (max-width: 768px) {
            body {
                padding: 10px;
            }
            
            header h1 {
                font-size: 1.5em;
            }
            
            .rating-value {
                font-size: 3em;
            }
            
            .header-info {
                flex-direction: column;
            }
        }
    """


def _get_rating_class(rating: Rating) -> str:
    """Get CSS class for rating."""
    rating_map = {
        Rating.A_PLUS_PLUS: "a-plus-plus",
        Rating.A_PLUS: "a-plus",
        Rating.A: "a",
        Rating.B: "b",
        Rating.C: "c",
        Rating.D: "d",
        Rating.E: "e",
        Rating.F: "f",
    }
    return rating_map.get(rating, "c")


def _generate_certificate_section(result: CheckResult) -> str:
    """Generate certificate section HTML."""
    html = """
        <section>
            <h2>Certificate Information</h2>
    """
    
    # Chain Check
    chain_severity = result.chain_check.severity.value.lower()
    html += f"""
            <div class="check-item {chain_severity}">
                <div class="check-label">Certificate Chain: <span class="severity-badge severity-{chain_severity}">{result.chain_check.severity.value}</span></div>
                <div class="check-value">
                    <strong>Subject:</strong> {result.chain_check.leaf_cert.subject}<br>
                    <strong>Issuer:</strong> {result.chain_check.leaf_cert.issuer}<br>
                    <strong>Serial Number:</strong> {result.chain_check.leaf_cert.serial_number}<br>
                    <strong>Chain Valid:</strong> {result.chain_check.chain_valid}<br>
                    <strong>Trust Store Valid:</strong> {result.chain_check.trust_store_valid}
                </div>
            </div>
    """
    
    # Hostname Check
    hostname_severity = result.hostname_check.severity.value.lower()
    html += f"""
            <div class="check-item {hostname_severity}">
                <div class="check-label">Hostname Matching: <span class="severity-badge severity-{hostname_severity}">{result.hostname_check.severity.value}</span></div>
                <div class="check-value">
                    <strong>Expected:</strong> {result.hostname_check.expected_hostname}<br>
                    <strong>Matches:</strong> {result.hostname_check.matches}
                </div>
            </div>
    """
    
    # Validity Check
    validity_severity = result.validity_check.severity.value.lower()
    html += f"""
            <div class="check-item {validity_severity}">
                <div class="check-label">Certificate Validity: <span class="severity-badge severity-{validity_severity}">{result.validity_check.severity.value}</span></div>
                <div class="check-value">
                    <strong>Valid:</strong> {result.validity_check.is_valid}<br>
                    <strong>Not Before:</strong> {result.validity_check.not_before.strftime('%Y-%m-%d %H:%M:%S UTC')}<br>
                    <strong>Not After:</strong> {result.validity_check.not_after.strftime('%Y-%m-%d %H:%M:%S UTC')}<br>
                    <strong>Days Until Expiry:</strong> {result.validity_check.days_until_expiry}
                </div>
            </div>
    """
    
    html += """
        </section>
    """
    return html


def _generate_protocol_section(result: CheckResult) -> str:
    """Generate protocol section HTML."""
    if not result.protocol_check:
        return '<section><h2>Protocol Versions</h2><p>Not checked (--skip-protocol)</p></section>'
    
    severity = result.protocol_check.severity.value.lower()
    html = f"""
        <section>
            <h2>Protocol Versions</h2>
            <div class="check-item {severity}">
                <div class="check-label">Status: <span class="severity-badge severity-{severity}">{result.protocol_check.severity.value}</span></div>
                <div class="check-value">
                    <strong>Supported Versions:</strong> {', '.join(result.protocol_check.supported_versions) if result.protocol_check.supported_versions else 'None'}<br>
                    <strong>Best Version:</strong> {result.protocol_check.best_version if result.protocol_check.best_version else 'None'}
    """
    
    if result.protocol_check.deprecated_versions:
        html += f'<br><strong>Deprecated Versions:</strong> {", ".join(result.protocol_check.deprecated_versions)} ⚠'
    
    if result.protocol_check.ssl_versions:
        html += f'<br><strong>SSL Versions (CRITICAL):</strong> {", ".join(result.protocol_check.ssl_versions)} ✗'
    
    html += """
                </div>
            </div>
        </section>
    """
    return html


def _generate_cipher_section(result: CheckResult) -> str:
    """Generate cipher section HTML."""
    if not result.cipher_check:
        return '<section><h2>Cipher Suites</h2><p>Not checked (--skip-cipher)</p></section>'
    
    severity = result.cipher_check.severity.value.lower()
    html = f"""
        <section>
            <h2>Cipher Suites</h2>
            <div class="check-item {severity}">
                <div class="check-label">Status: <span class="severity-badge severity-{severity}">{result.cipher_check.severity.value}</span></div>
                <div class="check-value">
                    <strong>Supported Ciphers:</strong> {len(result.cipher_check.supported_ciphers)}<br>
                    <strong>Perfect Forward Secrecy (PFS):</strong> {'Yes ✓' if result.cipher_check.pfs_supported else 'No ⚠'}<br>
                    <strong>Server Preferences:</strong> {'Yes' if result.cipher_check.server_preferences else 'No'}
                </div>
            </div>
    """
    
    if result.cipher_check.supported_ciphers:
        html += '<div class="cipher-list">'
        for cipher in result.cipher_check.supported_ciphers:
            is_weak = cipher in result.cipher_check.weak_ciphers
            css_class = "weak" if is_weak else ""
            html += f'<div class="cipher-item {css_class}">{cipher}</div>'
        html += '</div>'
    
    if result.cipher_check.weak_ciphers:
        html += f'<div class="check-value" style="margin-top: 10px;"><strong>Weak Ciphers:</strong> {", ".join(result.cipher_check.weak_ciphers)}</div>'
    
    html += """
        </section>
    """
    return html


def _generate_vulnerability_section(result: CheckResult) -> str:
    """Generate vulnerability section HTML."""
    if not result.vulnerability_checks:
        return '<section><h2>Cryptographic Vulnerabilities</h2><p>Not checked (--skip-vulnerabilities)</p></section>'
    
    html = """
        <section>
            <h2>Cryptographic Vulnerabilities</h2>
    """
    
    vulnerable_found = [v for v in result.vulnerability_checks if v.vulnerable]
    
    if vulnerable_found:
        html += f'<div class="check-item fail"><div class="check-label">Vulnerable: {len(vulnerable_found)} of {len(result.vulnerability_checks)}</div></div>'
    else:
        html += f'<div class="check-item ok"><div class="check-label">Vulnerable: 0 of {len(result.vulnerability_checks)}</div></div>'
    
    for vuln in result.vulnerability_checks:
        css_class = "vulnerable" if vuln.vulnerable else "safe"
        severity_badge = f'<span class="severity-badge severity-{vuln.severity.value.lower()}">{vuln.severity.value}</span>'
        html += f"""
            <div class="vulnerability-item {css_class}">
                <div class="check-label">{vuln.vulnerability_name} ({vuln.cve_id or "N/A"}): {severity_badge}</div>
                <div class="check-value">
                    <strong>Vulnerable:</strong> {vuln.vulnerable}<br>
                    <strong>Description:</strong> {vuln.description}
        """
        if vuln.recommendation:
            html += f'<br><strong>Recommendation:</strong> {vuln.recommendation}'
        html += """
                </div>
            </div>
        """
    
    html += """
        </section>
    """
    return html


def _generate_security_section(result: CheckResult) -> str:
    """Generate security best practices section HTML."""
    if not result.security_check:
        return '<section><h2>Security Best Practices</h2><p>Not checked (--skip-security)</p></section>'
    
    severity = result.security_check.severity.value.lower()
    html = f"""
        <section>
            <h2>Security Best Practices</h2>
            <div class="check-item {severity}">
                <div class="check-label">Status: <span class="severity-badge severity-{severity}">{result.security_check.severity.value}</span></div>
                <div class="check-value">
                    <strong>HSTS Enabled:</strong> {'Yes ✓' if result.security_check.hsts_enabled else 'No ⚠'}
    """
    
    if result.security_check.hsts_max_age:
        html += f'<br><strong>HSTS Max-Age:</strong> {result.security_check.hsts_max_age} seconds'
    
    html += f"""
                    <br><strong>OCSP Stapling:</strong> {'Yes ✓' if result.security_check.ocsp_stapling_enabled else 'No ⚠'}
                    <br><strong>TLS Compression:</strong> {'Enabled ✗ (CRIME vulnerability)' if result.security_check.tls_compression_enabled else 'Disabled ✓'}
                    <br><strong>Session Resumption:</strong> {'Yes ✓' if result.security_check.session_resumption_enabled else 'No'}
                </div>
            </div>
        </section>
    """
    return html


def _generate_crl_section(result: CheckResult) -> str:
    """Generate CRL section HTML."""
    html = """
        <section>
            <h2>CRL Distribution Points</h2>
    """
    
    # Group CRL checks by certificate type
    leaf_crl_checks = [c for c in result.crl_checks if c.certificate_type == "Leaf"]
    intermediate_crl_checks = [c for c in result.crl_checks if c.certificate_type == "Intermediate"]
    root_crl_checks = [c for c in result.crl_checks if c.certificate_type == "Root"]
    unknown_crl_checks = [c for c in result.crl_checks if not c.certificate_type]
    
    # Leaf certificate
    if result.chain_check.leaf_cert:
        html += '<h3>Leaf Certificate</h3>'
        if leaf_crl_checks:
            for crl in leaf_crl_checks:
                severity = crl.severity.value.lower()
                html += f"""
                    <div class="check-item {severity}">
                        <div class="check-label">URL: {crl.url} <span class="severity-badge severity-{severity}">{crl.severity.value}</span></div>
                        <div class="check-value">
                            <strong>Reachable:</strong> {crl.reachable}
                """
                if crl.status_code:
                    html += f'<br><strong>HTTP Status:</strong> {crl.status_code}'
                if crl.content_type:
                    html += f'<br><strong>Content-Type:</strong> {crl.content_type}'
                if crl.size_bytes:
                    size_str = f"{crl.size_bytes / 1024:.2f} KB" if crl.size_bytes < 1024 * 1024 else f"{crl.size_bytes / (1024 * 1024):.2f} MB"
                    html += f'<br><strong>Size:</strong> {size_str} ({crl.size_bytes} bytes)'
                if crl.error:
                    html += f'<br><strong>Error:</strong> {crl.error}'
                html += """
                        </div>
                    </div>
                """
        else:
            html += '<p>No CRL Distribution Points found</p>'
    
    # Intermediate certificates
    if result.chain_check.intermediate_certs:
        for idx, intermediate in enumerate(result.chain_check.intermediate_certs, 1):
            html += f'<h3>Intermediate Certificate {idx}</h3>'
            intermediate_crls = [c for c in intermediate_crl_checks if c.certificate_subject == intermediate.subject]
            if intermediate_crls:
                for crl in intermediate_crls:
                    severity = crl.severity.value.lower()
                    html += f"""
                        <div class="check-item {severity}">
                            <div class="check-label">URL: {crl.url} <span class="severity-badge severity-{severity}">{crl.severity.value}</span></div>
                            <div class="check-value">
                                <strong>Reachable:</strong> {crl.reachable}
                    """
                    if crl.status_code:
                        html += f'<br><strong>HTTP Status:</strong> {crl.status_code}'
                    if crl.content_type:
                        html += f'<br><strong>Content-Type:</strong> {crl.content_type}'
                    if crl.size_bytes:
                        size_str = f"{crl.size_bytes / 1024:.2f} KB" if crl.size_bytes < 1024 * 1024 else f"{crl.size_bytes / (1024 * 1024):.2f} MB"
                        html += f'<br><strong>Size:</strong> {size_str} ({crl.size_bytes} bytes)'
                    if crl.error:
                        html += f'<br><strong>Error:</strong> {crl.error}'
                    html += """
                            </div>
                        </div>
                    """
            else:
                html += '<p>No CRL Distribution Points found</p>'
    
    # Root certificate (only show if CRL URLs are present)
    if result.chain_check.root_cert and root_crl_checks:
        html += '<h3>Root Certificate</h3>'
        for crl in root_crl_checks:
            severity = crl.severity.value.lower()
            html += f"""
                <div class="check-item {severity}">
                    <div class="check-label">URL: {crl.url} <span class="severity-badge severity-{severity}">{crl.severity.value}</span></div>
                    <div class="check-value">
                        <strong>Reachable:</strong> {crl.reachable}
            """
            if crl.status_code:
                html += f'<br><strong>HTTP Status:</strong> {crl.status_code}'
            if crl.content_type:
                html += f'<br><strong>Content-Type:</strong> {crl.content_type}'
            if crl.size_bytes:
                size_str = f"{crl.size_bytes / 1024:.2f} KB" if crl.size_bytes < 1024 * 1024 else f"{crl.size_bytes / (1024 * 1024):.2f} MB"
                html += f'<br><strong>Size:</strong> {size_str} ({crl.size_bytes} bytes)'
            if crl.error:
                html += f'<br><strong>Error:</strong> {crl.error}'
            html += """
                    </div>
                </div>
            """
    
    # Unknown certificates (fallback)
    if unknown_crl_checks:
        for crl in unknown_crl_checks:
            severity = crl.severity.value.lower()
            html += f"""
                <div class="check-item {severity}">
                    <div class="check-label">URL: {crl.url} <span class="severity-badge severity-{severity}">{crl.severity.value}</span></div>
                    <div class="check-value">
                        <strong>Reachable:</strong> {crl.reachable}
            """
            if crl.status_code:
                html += f'<br><strong>HTTP Status:</strong> {crl.status_code}'
            if crl.content_type:
                html += f'<br><strong>Content-Type:</strong> {crl.content_type}'
            if crl.size_bytes:
                size_str = f"{crl.size_bytes / 1024:.2f} KB" if crl.size_bytes < 1024 * 1024 else f"{crl.size_bytes / (1024 * 1024):.2f} MB"
                html += f'<br><strong>Size:</strong> {size_str} ({crl.size_bytes} bytes)'
            if crl.error:
                html += f'<br><strong>Error:</strong> {crl.error}'
            html += """
                    </div>
                </div>
            """
    
    # If no CRL checks at all
    if not result.crl_checks:
        html += '<p>No CRL Distribution Points found in any certificate</p>'
    
    html += """
        </section>
    """
    return html


def _generate_ocsp_section(result: CheckResult) -> str:
    """Generate OCSP section HTML."""
    if not result.ocsp_checks:
        return '<section><h2>OCSP Responders</h2><p>None found</p></section>'
    
    html = """
        <section>
            <h2>OCSP Responders</h2>
    """
    
    for ocsp in result.ocsp_checks:
        severity = ocsp.severity.value.lower()
        html += f"""
            <div class="check-item {severity}">
                <div class="check-label">URL: {ocsp.url} <span class="severity-badge severity-{severity}">{ocsp.severity.value}</span></div>
                <div class="check-value">
                    <strong>Reachable:</strong> {ocsp.reachable}
        """
        
        if ocsp.status_code:
            html += f'<br><strong>HTTP Status:</strong> {ocsp.status_code}'
        if ocsp.error:
            html += f'<br><strong>Error:</strong> {ocsp.error}'
        
        html += """
                </div>
            </div>
        """
    
    html += """
        </section>
    """
    return html

